name: GitHub Pages

on:
  push:
    branches:
      - trunk
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ 'pull_request' == github.event_name && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install npm dependencies
      run: npm ci

    - name: Build
      run: npm run build:docs

    - name: Deploy
      run: |
        git config --global user.name "branch-sync[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        npm run gh-pages
